server:
  port: 8082

spring:
  application:
    name: ride-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ridedb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true