version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: uber
      POSTGRES_PASSWORD: password
      POSTGRES_DB: miniuber
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
