server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      # Optional: auto-create routes from serviceId (if you like /SERVICE-ID/** style)
      discovery:
        locator:
          enabled: false   # keep false since you're defining routes manually
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**
          filters:
            - StripPrefix=1

        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/rides/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1

        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/tracking/**
          filters:
            - StripPrefix=1

        - id: matching-service
          uri: lb://matching-service
          predicates:
            - Path=/api/matching/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
