spring:
  application:
    name: driver-service           # change per service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
  datasource:
    url: jdbc:postgresql://localhost:5436/driverdb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop   # auto creates schema on startup
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always