spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/driverdb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop   # auto creates schema on startup
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8082
